name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shell: [pwsh, powershell]
        exclude:
          - os: ubuntu-latest
            shell: powershell
          - os: macos-latest
            shell: powershell
    steps:
      - name: Run Pester Tests
        id: pester
        uses: zyborg/pester-tests-report@v1
        with:
          report_name: TestResults_${{ runner.os }}_${{ matrix.shell }}
          tests_fail_step: true
          coverage_report_name: CoverageResults_${{ runner.os }}_${{ matrix.shell }}
